---
- name: Obtener Informacion
  hosts: sw_to_bck
  tasks:
    - name: "BACKUP: IOS CONFIG to FTP"
      ios_command:
        command: copy running-config ftp://172.31.15.252
        prompt: "Address or name of remote host \\[172.31.15.252\\]??"
        answer: "\n"