---
- name: Obtener Informacion
  hosts: switches
  tasks:
    - name: "BACKUP: IOS CONFIG to TFTP"
      ansible.netcommon.cli_command:
        command: copy running-config tftp://172.16.14.200
        prompt: "Address or name of remote host \\[172.16.14.200\\]?"
        answer: "\n"